### ISSUE TITLE
Sooty Pig Textures Broken

### ISSUE THREAD

**Issue by OmegaDovah** [Slexom/earth2java#105]
The textures of sooty pig are broken on version "earth2java-forge-1.10.0+1.19.2"
![image](https://github.com/Slexom/earth2java/assets/105981820/57e798fd-f1fe-47b6-b9ed-cba96639537e)

**Comment by Slexom** [comment]
released just now 1.10.0b that solve the issue.
Fixed it in 1.19.4 but not backported to 1.19.2 :(

**Comment by OmegaDovah** [comment]
Seems like that did not fix it
![image](https://github.com/Slexom/earth2java/assets/105981820/4291f9a2-0653-403a-8ccb-a4bde714ab2c)

**Comment by OmegaDovah** [comment]
> released just now 1.10.0b that solve the issue. Fixed it in 1.19.4 but not backported to 1.19.2 :(

Did you test this update on your end? did it work as intended for you
